# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jsdata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jsdata.proto',
  package='joystick',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cjsdata.proto\x12\x08joystick\"\x8e\x02\n\tJSMessage\x12\n\n\x02id\x18\x01 \x01(\x11\x12-\n\x07\x62uttons\x18\x02 \x03(\x0b\x32\x1c.joystick.JSMessage.JSButton\x12(\n\x04\x61xes\x18\x03 \x03(\x0b\x32\x1a.joystick.JSMessage.JSAxis\x12\'\n\x04hats\x18\x04 \x03(\x0b\x32\x19.joystick.JSMessage.JSHat\x1a*\n\x08JSButton\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nis_pressed\x18\x02 \x01(\x08\x1a#\n\x06JSAxis\x12\n\n\x02id\x18\x01 \x01(\x11\x12\r\n\x05value\x18\x02 \x01(\x11\x1a\"\n\x05JSHat\x12\n\n\x02id\x18\x01 \x01(\x11\x12\r\n\x05value\x18\x02 \x01(\x11\x62\x06proto3')
)




_JSMESSAGE_JSBUTTON = _descriptor.Descriptor(
  name='JSButton',
  full_name='joystick.JSMessage.JSButton',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='joystick.JSMessage.JSButton.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_pressed', full_name='joystick.JSMessage.JSButton.is_pressed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=224,
)

_JSMESSAGE_JSAXIS = _descriptor.Descriptor(
  name='JSAxis',
  full_name='joystick.JSMessage.JSAxis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='joystick.JSMessage.JSAxis.id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='joystick.JSMessage.JSAxis.value', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=261,
)

_JSMESSAGE_JSHAT = _descriptor.Descriptor(
  name='JSHat',
  full_name='joystick.JSMessage.JSHat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='joystick.JSMessage.JSHat.id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='joystick.JSMessage.JSHat.value', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=297,
)

_JSMESSAGE = _descriptor.Descriptor(
  name='JSMessage',
  full_name='joystick.JSMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='joystick.JSMessage.id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buttons', full_name='joystick.JSMessage.buttons', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='axes', full_name='joystick.JSMessage.axes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hats', full_name='joystick.JSMessage.hats', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_JSMESSAGE_JSBUTTON, _JSMESSAGE_JSAXIS, _JSMESSAGE_JSHAT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=297,
)

_JSMESSAGE_JSBUTTON.containing_type = _JSMESSAGE
_JSMESSAGE_JSAXIS.containing_type = _JSMESSAGE
_JSMESSAGE_JSHAT.containing_type = _JSMESSAGE
_JSMESSAGE.fields_by_name['buttons'].message_type = _JSMESSAGE_JSBUTTON
_JSMESSAGE.fields_by_name['axes'].message_type = _JSMESSAGE_JSAXIS
_JSMESSAGE.fields_by_name['hats'].message_type = _JSMESSAGE_JSHAT
DESCRIPTOR.message_types_by_name['JSMessage'] = _JSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JSMessage = _reflection.GeneratedProtocolMessageType('JSMessage', (_message.Message,), dict(

  JSButton = _reflection.GeneratedProtocolMessageType('JSButton', (_message.Message,), dict(
    DESCRIPTOR = _JSMESSAGE_JSBUTTON,
    __module__ = 'jsdata_pb2'
    # @@protoc_insertion_point(class_scope:joystick.JSMessage.JSButton)
    ))
  ,

  JSAxis = _reflection.GeneratedProtocolMessageType('JSAxis', (_message.Message,), dict(
    DESCRIPTOR = _JSMESSAGE_JSAXIS,
    __module__ = 'jsdata_pb2'
    # @@protoc_insertion_point(class_scope:joystick.JSMessage.JSAxis)
    ))
  ,

  JSHat = _reflection.GeneratedProtocolMessageType('JSHat', (_message.Message,), dict(
    DESCRIPTOR = _JSMESSAGE_JSHAT,
    __module__ = 'jsdata_pb2'
    # @@protoc_insertion_point(class_scope:joystick.JSMessage.JSHat)
    ))
  ,
  DESCRIPTOR = _JSMESSAGE,
  __module__ = 'jsdata_pb2'
  # @@protoc_insertion_point(class_scope:joystick.JSMessage)
  ))
_sym_db.RegisterMessage(JSMessage)
_sym_db.RegisterMessage(JSMessage.JSButton)
_sym_db.RegisterMessage(JSMessage.JSAxis)
_sym_db.RegisterMessage(JSMessage.JSHat)


# @@protoc_insertion_point(module_scope)
