#!/bin/bash

if [ "$1" == "help" ]; then	
	echo "Builds and runs the specified nodes only if the build succeeds"
	echo "Usage: ./scripts/build_run tony                      | Builds and runs tony"
    echo "     : ./scripts/build_run [package1, package2 ...]  | Builds and runs all specified packages"
    exit
fi




# Let script run from top level or scripts folder
if [ -z "$1" ]
  then
    echo "ERROR: No argument supplied. Did you mean to have tony as an arg?"
    exit
fi

SCRIPT=`realpath $0`
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

if [ $SCRIPTPATH == `pwd` ]; then
  cd ..
fi

source `pwd`/devel/setup.bash

if ./scripts/manual_build tony; then
	echo "Build suceeded"
	./scripts/manual_run $@
else
	echo "Build FAILED. Not running requested nodes. Please make sure your file builds correctly."
fi