#!/bin/bash

# Let script run from top level or scripts folder
SCRIPT=`realpath $0`
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

if [ $SCRIPTPATH == `pwd` ]; then
  cd ..
fi

`pwd`/devel/setup.bash

# Let script run from top level or scripts folder
if [ -z "$1" ]; then
    catkin_make
else
	if [ "$1" == "communication" ]; then
  		catkin_make --pkg tony
  	else
		catkin_make --pkg $1
	fi
fi


