#!/bin/bash

if [ "$1" == "help" ]; then	
	echo "Cleans all packages."
	echo "Usage: ./scripts/clean | Cleans everything"
    exit
fi

# Let script run from top level or scripts folder
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

if [ $SCRIPTPATH == `pwd` ]; then
  cd ..
fi

source `pwd`/devel/setup.bash
catkin_make clean