#!/bin/bash

if [ "$1" == "help" ]; then	
	echo "Builds various packages."
	echo "Usage: ./scripts/manual_build            | defaults to building tony"
    echo "     : ./scripts/manual_build tony       | builds tony"
    echo "     : ./scripts/manual_build all        | builds all packages"
    echo "     : ./scripts/manual_build [package]  | builds package"
    exit
fi


# Let script run from top level or scripts folder
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`
MAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-Wall -DCMAKE_C_FLAGS=-Wall"

if [ $SCRIPTPATH == `pwd` ]; then
  cd ..
fi

source `pwd`/devel/setup.bash


lower_case=$(echo "$1" | tr '[:upper:]' '[:lower:]')
# if [ "$lower_case" == "tony" ]; then
# 	roslaunch ./launch/tony.launch
# 	exit
# fi

launch_file="./launch/dummy_debug.launch"

echo "<launch>" > $launch_file


debug_arg=false
for arg in "$@"; do
	lower_case=$(echo "$arg" | tr '[:upper:]' '[:lower:]')

	if [ $lower_case == "-d" ]; then
		debug_arg=true
		continue
  	else
  		if $debug_arg; then
  			echo "<node name=\"$lower_case\" pkg=\"tony\" type=\"$lower_case\" output=\"screen\" launch-prefix=\"xterm -e cgdb -ex start --args\"/>" >> $launch_file
			debug_arg=false
		else
			echo "<node name=\"$lower_case\" pkg=\"tony\" type=\"$lower_case\" output=\"screen\" />" >> $launch_file
		fi
	fi

done
echo "</launch>" >> $launch_file


sudo ./scripts/manual_launch dummy_debug