#!/bin/bash

if [ "$1" == "help" ]; then	
	echo "Launches the specified launch file"
	echo "Usage: ./scripts/manual_launch tony               | runs tony"
    echo "     : ./scripts/manual_launch beginner_tutorials | runs beginner_tutorials"
    echo "     : ./scripts/manual_launch [launch_file]      | runs launch_file"
    exit
fi

# Let script run from top level or scripts folder
if [ -z "$1" ]
  then
    echo "ERROR: No argument supplied. Did you mean to have tony as an arg?"
    exit
fi

SCRIPT=`realpath $0`
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

if [ $SCRIPTPATH == `pwd` ]; then
  cd ..
fi

source `pwd`/devel/setup.bash

lower_case=$(echo "$1" | tr '[:upper:]' '[:lower:]')
roslaunch launch/$lower_case.launch