#!/bin/bash

if [ "$1" == "help" ]; then	
	echo "Builds various packages."
	echo "Usage: ./scripts/manual_build            | defaults to building tony"
    echo "     : ./scripts/manual_build tony       | builds tony"
    echo "     : ./scripts/manual_build all        | builds all packages"
    echo "     : ./scripts/manual_build [package]  | builds package"
    exit
fi


# Let script run from top level or scripts folder
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`
MAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-Wall -DCMAKE_C_FLAGS=-Wall"

if [ $SCRIPTPATH == `pwd` ]; then
  cd ..
fi

source `pwd`/devel/setup.bash

# Let script run from top level or scripts folder
if [ -z "$1" ]; then
    catkin_make $MAKE_FLAGS --pkg tony
else
	lower_case=$(echo "$1" | tr '[:upper:]' '[:lower:]')
	if [ "$lower_case" == "all" ]; then
		catkin_make $MAKE_FLAGS
		exit
	fi

	if [ "$lower_case" == "communication" ]; then
  		catkin_make $MAKE_FLAGS --pkg tony
  	else
  		catkin_make $MAKE_FLAGS --pkg $lower_case
	fi
fi


