#!/bin/bash

# Let script run from top level or scripts folder
if [ -z "$1" ]
  then
    echo "ERROR: No argument supplied. Did you mean to have tony as an arg?"
    exit
fi

SCRIPT=`realpath $0`
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

if [ $SCRIPTPATH == `pwd` ]; then
  cd ..
fi

`pwd`/devel/setup.bash
roslaunch launch/$1.launch